### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by ghost** [LiLuo-B/nonebot-plugin-valve-server-query#2]
nonebot v2.3.2报错
```
07-30 22:07:48 [ERROR] nonebot | Failed to import "nonebot_plugin_valve_server_query"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/root/awero/.venv/lib/python3.9/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/awero/.venv/lib/python3.9/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/awero/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/root/awero/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/awero/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/awero/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/awero/.venv/lib/python3.9/site-packages/nonebot_plugin_valve_server_query/__init__.py", line 2, in <module>
    from . import __main__ as __main__
  File "/root/awero/.venv/lib/python3.9/site-packages/nonebot_plugin_valve_server_query/__main__.py", line 2, in <module>
    from .queries import queries_server_info, queries_group_info
  File "/root/awero/.venv/lib/python3.9/site-packages/nonebot_plugin_valve_server_query/queries.py", line 4, in <module>
    from .database import valve_db
  File "/root/awero/.venv/lib/python3.9/site-packages/nonebot_plugin_valve_server_query/database.py", line 9, in <module>
    class ValveServerSqlite:
  File "/root/awero/.venv/lib/python3.9/site-packages/nonebot_plugin_valve_server_query/database.py", line 83, in ValveServerSqlite
    def get_valve_server_ip(self, group_name: str, server_id: int) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by ghost** [comment]
authority.json配置
```
{
	"测试": [
		"QQ号"
	]
}
```
server.json配置
```
{
    "测试": [
        {
            "id": 1,
            "ip": "127.0.0.1:27015"
        }
    ]
}
```

**Comment by LiLuo-B** [comment]
大概知道啥问题 空了修

**Comment by LiLuo-B** [comment]
现在试试看

**Comment by ghost** [comment]
解决了，感谢修复
